//------------------------------------------------------------------------------
//  After Add/Update/Configure Service Reference find the Reference.cs file
//		add the "#pragma warning disable 1591" at the top
//------------------------------------------------------------------------------
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWR.IssueTracker.UI.IssuesServiceWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/RWR.MessageContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RWR.IssueTracker.UI.IssuesServiceWCF.UpdateIssuesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RWR.IssueTracker.UI.IssuesServiceWCF.GetPriorityTypeCodesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RWR.IssueTracker.UI.IssuesServiceWCF.GetIssuesRequest))]
    public partial class BaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClientTransactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClientTransactionId {
            get {
                return this.ClientTransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientTransactionIdField, value) != true)) {
                    this.ClientTransactionIdField = value;
                    this.RaisePropertyChanged("ClientTransactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateIssuesRequest", Namespace="http://schemas.datacontract.org/2004/07/RWR.MessageContracts.Issues")]
    [System.SerializableAttribute()]
    public partial class UpdateIssuesRequest : RWR.IssueTracker.UI.IssuesServiceWCF.BaseRequest {
        
        private RWR.IssueTracker.DSBO.IssuesCD IssuesCDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public RWR.IssueTracker.DSBO.IssuesCD IssuesCD {
            get {
                return this.IssuesCDField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuesCDField, value) != true)) {
                    this.IssuesCDField = value;
                    this.RaisePropertyChanged("IssuesCD");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPriorityTypeCodesRequest", Namespace="http://schemas.datacontract.org/2004/07/RWR.MessageContracts.Issues")]
    [System.SerializableAttribute()]
    public partial class GetPriorityTypeCodesRequest : RWR.IssueTracker.UI.IssuesServiceWCF.BaseRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetIssuesRequest", Namespace="http://schemas.datacontract.org/2004/07/RWR.MessageContracts.Issues")]
    [System.SerializableAttribute()]
    public partial class GetIssuesRequest : RWR.IssueTracker.UI.IssuesServiceWCF.BaseRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/RWR.MessageContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RWR.IssueTracker.UI.IssuesServiceWCF.UpdateIssuesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RWR.IssueTracker.UI.IssuesServiceWCF.GetPriorityTypeCodesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RWR.IssueTracker.UI.IssuesServiceWCF.GetIssuesResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateIssuesResponse", Namespace="http://schemas.datacontract.org/2004/07/RWR.MessageContracts.Issues")]
    [System.SerializableAttribute()]
    public partial class UpdateIssuesResponse : RWR.IssueTracker.UI.IssuesServiceWCF.BaseResponse {
        
        private RWR.IssueTracker.DSBO.IssuesCD IssuesCDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public RWR.IssueTracker.DSBO.IssuesCD IssuesCD {
            get {
                return this.IssuesCDField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuesCDField, value) != true)) {
                    this.IssuesCDField = value;
                    this.RaisePropertyChanged("IssuesCD");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPriorityTypeCodesResponse", Namespace="http://schemas.datacontract.org/2004/07/RWR.MessageContracts.Issues")]
    [System.SerializableAttribute()]
    public partial class GetPriorityTypeCodesResponse : RWR.IssueTracker.UI.IssuesServiceWCF.BaseResponse {
        
        private RWR.IssueTracker.DSBO.CodesCD CodesCDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public RWR.IssueTracker.DSBO.CodesCD CodesCD {
            get {
                return this.CodesCDField;
            }
            set {
                if ((object.ReferenceEquals(this.CodesCDField, value) != true)) {
                    this.CodesCDField = value;
                    this.RaisePropertyChanged("CodesCD");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetIssuesResponse", Namespace="http://schemas.datacontract.org/2004/07/RWR.MessageContracts.Issues")]
    [System.SerializableAttribute()]
    public partial class GetIssuesResponse : RWR.IssueTracker.UI.IssuesServiceWCF.BaseResponse {
        
        private RWR.IssueTracker.DSBO.IssuesCD IssuesCDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public RWR.IssueTracker.DSBO.IssuesCD IssuesCD {
            get {
                return this.IssuesCDField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuesCDField, value) != true)) {
                    this.IssuesCDField = value;
                    this.RaisePropertyChanged("IssuesCD");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnspecifiedFault", Namespace="http://www.RobertRisley.com/2010")]
    [System.SerializableAttribute()]
    public partial class UnspecifiedFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnspecifiedMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnspecifiedMessage {
            get {
                return this.UnspecifiedMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.UnspecifiedMessageField, value) != true)) {
                    this.UnspecifiedMessageField = value;
                    this.RaisePropertyChanged("UnspecifiedMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.RobertRisley.com/2010", ConfigurationName="IssuesServiceWCF.IssuesContract")]
    public interface IssuesContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="GetIssues", ReplyAction="http://www.RobertRisley.com/2010/IssuesContract/GetIssuesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RWR.IssueTracker.UI.IssuesServiceWCF.UnspecifiedFault), Action="http://www.RobertRisley.com/2010/IssuesContract/GetIssuesUnspecifiedFault", Name="UnspecifiedFault")]
        RWR.IssueTracker.UI.IssuesServiceWCF.GetIssuesResponse GetIssues(RWR.IssueTracker.UI.IssuesServiceWCF.GetIssuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UpdateIssues", ReplyAction="http://www.RobertRisley.com/2010/IssuesContract/UpdateIssuesResponse")]
        RWR.IssueTracker.UI.IssuesServiceWCF.UpdateIssuesResponse UpdateIssues(RWR.IssueTracker.UI.IssuesServiceWCF.UpdateIssuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetPriorityTypeCodes", ReplyAction="http://www.RobertRisley.com/2010/IssuesContract/GetPriorityTypeCodesResponse")]
        RWR.IssueTracker.UI.IssuesServiceWCF.GetPriorityTypeCodesResponse GetPriorityTypeCodes(RWR.IssueTracker.UI.IssuesServiceWCF.GetPriorityTypeCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ping", ReplyAction="http://www.RobertRisley.com/2010/IssuesContract/PingResponse")]
        string Ping();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IssuesContractChannel : RWR.IssueTracker.UI.IssuesServiceWCF.IssuesContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IssuesContractClient : System.ServiceModel.ClientBase<RWR.IssueTracker.UI.IssuesServiceWCF.IssuesContract>, RWR.IssueTracker.UI.IssuesServiceWCF.IssuesContract {
        
        public IssuesContractClient() {
        }
        
        public IssuesContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IssuesContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IssuesContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IssuesContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RWR.IssueTracker.UI.IssuesServiceWCF.GetIssuesResponse GetIssues(RWR.IssueTracker.UI.IssuesServiceWCF.GetIssuesRequest request) {
            return base.Channel.GetIssues(request);
        }
        
        public RWR.IssueTracker.UI.IssuesServiceWCF.UpdateIssuesResponse UpdateIssues(RWR.IssueTracker.UI.IssuesServiceWCF.UpdateIssuesRequest request) {
            return base.Channel.UpdateIssues(request);
        }
        
        public RWR.IssueTracker.UI.IssuesServiceWCF.GetPriorityTypeCodesResponse GetPriorityTypeCodes(RWR.IssueTracker.UI.IssuesServiceWCF.GetPriorityTypeCodesRequest request) {
            return base.Channel.GetPriorityTypeCodes(request);
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
    }
}
